config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :battles, only: %i[index show new create] do
    collection do
      get :index_ongoing
      get :history
    end
    resources :votes, only: %i[create]
  end
  resources :responses, only: %i[index create]

  get "/about", to: "pages#about"
  get "/legal", to: "pages#legal"
  get "/team",  to: "pages#team"
  get "/leaderboards", to: "pages#leaderboards"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/battle.rb
class Battle < ApplicationRecord
  belongs_to :user
  has_many :responses
  has_many :votes

  validates :category, :end_date, :prompt, presence: true
  after_save :async_responses_call

  private

  def async_responses_call
    jobs = [AskClaudeJob.new(self), AskOpenAiJob.new(self), AskMistralJob.new(self)]
    ActiveJob.perform_all_later(jobs)
  end
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :battle
  has_many :votes

  validates :model, presence: true

  CATEGORIES = {
    keyboard: 'Content',
    'magnifying-glass': 'Research',
    comments: 'Discussion',
    calculator: 'Mathematics'
  }

  DURATIONS = {
    '30 mins': (DateTime.now + 30.minutes),
    '1 hour': (DateTime.now + 1.hour),
    '2 hours': (DateTime.now + 2.hours),
    '1 day': (DateTime.now + 1.day)
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :battles
  has_many :votes
  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :pseudo, uniqueness: true
  # validates :photo, content_type: ['image/png', 'image/jpg', 'image/jpeg'], size: { less_than: 5.megabytes }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :battle
  belongs_to :user
  belongs_to :response

  def self.user_voted?(user, battle)
    exists?(user: user, battle: battle)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:pseudo, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:pseudo, :photo])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  before_action :set_desc_ongoing_battles, only: [:index_ongoing]
  before_action :set_desc_past_battles, only: [:history]

  def index
    @battles = Battle.all
    @past_battles = set_desc_past_battles
    @ongoing_battles = set_desc_ongoing_battles
  end

  def index_ongoing
    if params[:filters].present?
      selected_categories = params[:filters].keys
      @battles = @battles.where(category: selected_categories)
    end

    if params[:winners].present?
      selected_winners = params[:winners].keys
      @battles = @battles.where(winner: selected_winners)
    end
    render "index_ongoing"
  end

  def history
    if params[:filters].present?
      selected_categories = params[:filters].keys
      @battles = @battles.where(category: selected_categories)
    end

    if params[:winners].present?
      selected_winners = params[:winners].keys
      @battles = @battles.where(winner: selected_winners)
    end

    render "history"
  end

  def show
    @battle = Battle.find(params[:id])
    @responses = @battle.responses
    @vote = Vote.find_by(user: current_user, battle: @battle)

    @votes_count_ranking = @responses.map { |response| response.votes.count }.sort_by { |response| -response }

    @ranking = @responses.sort_by { |response| -response.votes.count }.map(&:model)

    @votes_count = 0
    @responses.each { |response| @votes_count += response.votes.count }

    @all_votes_count = {
      "Claude" => Vote.joins(:response).where(responses: { model: "Claude" }).count,
      "OpenAI" => Vote.joins(:response).where(responses: { model: "OpenAI" }).count,
      "Mistral" => Vote.joins(:response).where(responses: { model: "Mistral" }).count
    }
    # Trier par nombre de votes décroissant
    @sorted_votes = @all_votes_count.sort_by { |_, votes| -votes }.to_h
    # Récupérer la liste des modèles triés par nombre de votes
    @sorted_models = @sorted_votes.keys
    # Récupérer la liste des votes triés
    @sorted_vote_counts = @sorted_votes.values
  end

  def new
    @battle = Battle.new
  end

  def create
    @battle = Battle.new(battle_params)
    @battle.user = current_user
    if @battle.save
      create_responses(@battle)
      flash[:notice] = "Battle successfully created"
      redirect_to battle_path(@battle)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def battle_params
    params.require(:battle).permit(:category, :end_date, :prompt)
  end

  def create_responses(battle)
    models = ["Claude", "OpenAI", "Mistral"]
    models.shuffle.each do |model|
      Response.create(model: model, battle: battle)
    end
  end

  def set_desc_past_battles
    @battles = Battle.where.not(winner: nil).order(created_at: :desc)
  end

  def set_desc_ongoing_battles
    @battles = Battle.where(winner: nil).order(created_at: :desc)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @battle = Battle.find(params[:battle_id])
    @response = Response.find(params[:response_id])
    @responses = @battle.responses

    if Vote.user_voted?(current_user, @battle)
      redirect_to battle_path(@battle)
      flash[:alert] = "You already voted"
    else
      @vote = Vote.new
      @vote.user = current_user
      @vote.battle = @battle
      @vote.response = @response

      if @vote.save
        redirect_to battle_path(@battle)
        flash[:notice] = "Your vote has been registered"
      else
        render 'battles/show', status: :unprocessable_entity
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_to_html(text)
    renderer = Redcarpet::Render::HTML.new
    markdown = Redcarpet::Markdown.new(renderer, autolink: true, tables: true)
    markdown.render(text).html_safe
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/battles/_icons.html.erb
<div>
  <div id='category-<%= category[1] %>'>
    <i class='fa-solid fa-<%= category[0] %>'></i>
    <%= category[1] %>
  </div>
</div>

app/views/battles/index.html.erb
<script>
        const monContainer = document.getElementById("unid");
        function toLeft(container, scrollDistance) {
          container.scrollBy({left: -scrollDistance, behavior: "smooth"});
        }

        function toRight(container, scrollDistance) {
          container.scrollBy({left: scrollDistance, behavior: "smooth"});
        }
  </script>

<script>
    document.addEventListener("turbo:load", function () {
        const cards = document.querySelectorAll(".prompt-card-third-row");
        const buttonMore = document.getElementById("loadMore");
        const buttonLess = document.getElementById("loadLess");
        let visibleCount = 0;

        function showMoreCards(shouldScroll = true) {
            let nextCards = Array.from(cards).slice(visibleCount, visibleCount + 3);
            nextCards.forEach(card => card.classList.remove("hidden"));
            visibleCount += 3;

            if (visibleCount >= cards.length) {
                buttonMore.style.display = "none";
            }

            if (visibleCount > 3) {
              buttonLess.style.display = "inline";
        }

          if (shouldScroll) {
            window.scrollBy({ top: 240, behavior: "smooth"});
          }

        }

        function showLessCards() {
        if (visibleCount > 3) {
            let lastCards = Array.from(cards).slice(visibleCount - 3, visibleCount);
            lastCards.forEach(card => card.classList.add("hidden"));
            visibleCount -= 3;
        }

        if (visibleCount <= 3) {
            buttonLess.style.display = "none";
        }

        if (visibleCount < cards.length) {
            buttonMore.style.display = "inline";
        }
        window.scrollBy({ top: -240, behavior: "smooth"});
      }

        showMoreCards(false);

        buttonMore.addEventListener("click", showMoreCards);
        buttonLess.addEventListener("click", showLessCards);
    });
</script>

<div class="index-container">
  <h1 class="title-index"> <%= "Welcome back, #{current_user.pseudo} !" %> </h1>

      <div class="index-first-row">
        <div class="user-infos-index">
          <div class="user-infos-image">
            <%#= cl_image_tag current_user.photo.key, class: 'avatar-square-large', default_image: 'Default_avatar.jpeg' %>
            <% if current_user.photo.key.present? %>
              <%= cl_image_tag(current_user.photo.key, class: 'avatar-square-large') %>
            <% else %>
              <%= image_tag('Default_avatar.jpeg', class: 'avatar-square-large') %>
            <% end %>
          </div>
          <div class="infos-user-left">
              <div class="user-infos-text">

                <div class="square-info">
                  <div class="square-info-title">Prompts</div>
                  <div class="square-info-bottom">
                    <i class="fa-solid fa-terminal"></i><span><%= current_user.battles.count %></span>
                  </div>
                </div>
                <div class="square-info">
                  <div class="square-info-title">Votes</div>
                  <div class="square-info-bottom">
                    <i class="fa-solid fa-heart"></i><span><%= current_user.votes.count %></span>
                  </div>
                </div>
                <div class="square-info">
                  <div class="square-info-title">Votes received</div>
                  <div class="square-info-bottom">

                    <% votes = 0 %>
                    <% current_user.battles.each do |battle| %>
                      <% votes += battle.votes.count %>
                    <% end %>

                    <i class="fa-solid fa-check-to-slot"></i><span><%= votes %></span>
                  </div>
                </div>
                <div class="square-info">
                  <div class="square-info-title">Rank</div>
                  <div class="square-info-bottom">
                    <i class="fa-solid fa-ranking-star"></i><span>Noob</span>
                  </div>
                </div>

            </div>
          </div>
        </div>

          <div class="button"><%= button_to "Start a new battle", new_battle_path, method: :get, class: "button-new" %></div>

            <div class="ia-right">
              <div class="all-logos">
                  <div class="logo-with-name">
                    <div class="logo-name">Claude</div>
                    <%= image_tag "logos_ai/claude.png", alt: "logo", class: " logo" %>
                  </div>

                  <div class="logo-with-name">
                    <div class="logo-name">Deepseek</div>
                    <%= image_tag "logos_ai/deepseek.png", alt: "logo", class: "logo" %>
                  </div>

                  <div class="logo-with-name">
                    <div class="logo-name">Grok</div>
                    <%= image_tag "logos_ai/grok.png", alt: "logo", class: "logo" %>
                  </div>

                  <div class="logo-with-name">
                    <div class="logo-name">Mistral</div>
                    <%= image_tag "logos_ai/Mistral.png", alt: "logo", class: " logo" %>
                  </div>

                <div class="logo-with-name">
                  <div class="logo-name">ChatGPT</div>
                  <%= image_tag "logos_ai/chatgpt.png", alt: "logo", class: " logo" %>
                </div>

                <div class="logo-with-name">
                  <div class="logo-name">Meta</div>
                  <%= image_tag "logos_ai/meta.png", alt: "logo", class: " logo" %>
                </div>
            </div>
          </div>
      </div>

      <h2 class="second-title">My battles</h2>
        <div class="index-second-row" id="unid">

        <% if current_user.battles.any? %>
          <% current_user.battles.order(created_at: :desc).each do |battle| %>
              <%= link_to battle_path(battle), class: 'text-decoration-none' do %>
                <div class="prompt-card">
                  <div class="prompt-top"><p><%= battle.prompt %></p></div>

                    <div class="prompt-card-body">
                      <div class="first-elements-card">
                        <div class="category"><%= battle.category.capitalize %></div>
                        <div class="battle-vote-count">
                          <i class="fa-solid fa-check-to-slot"></i>
                          <%= "#{battle.votes.count}" %>
                        </div>
                      </div>
                        <div class="last-elements-card">
                          <div class="pseudo"><%= "#{battle.user.pseudo}" %></div>
                          <div class="status">
                            <% status = if battle.winner %>
                              <%= content_tag(:i, '', class: 'fa-solid fa-trophy') %><%= "#{battle.winner}" %>
                            <% else %>
                              <%= content_tag(:i, '', class: 'fa-solid fa-clock') %>
                              <% seconds_until_target_time = battle.end_date.to_time.to_i - Time.now.to_i %>
                              <%= content_tag(:p, "", data: {
                                    controller: "timer",
                                    timer_target: "timer",
                                    seconds_until_end_value: seconds_until_target_time
                                  }) %>
                            <% end %>
                          </div>
                        </div>
                    </div>
                </div>
              <% end %>
          <% end %>
        <% else %>
          <p class="text-no-battle">You've not created any battle yet !</p>
        <% end %>
      </div>

          <% if current_user.battles.count > 3 %>
              <div class="button-row">
                <button class="button-slide" onclick="toLeft(unid, 500)"><i class="fa-solid fa-arrow-left"></i></button>
                <button class="button-slide" onclick="toRight(unid, 500)"><i class="fa-solid fa-arrow-right"></i></button>
              </div>
          <% end %>

    <div class="third-row-index">
      <h2 class="second-title">Opened battles</h2>
        <div class="index-third-row" id="itemContainer">

          <% @ongoing_battles.each do |battle| %>
              <%= link_to battle_path(battle), class: 'text-decoration-none' do %>
                <div class="prompt-card-third-row hidden">
                  <div class="prompt-top"><p><%= battle.prompt %></p></div>

                    <div class="prompt-card-body">
                      <div class="first-elements-card">
                        <div class="category"><%= battle.category.capitalize %></div>
                        <div class="battle-vote-count">
                          <i class="fa-solid fa-check-to-slot"></i>
                          <%= "#{battle.votes.count}" %>
                        </div>
                      </div>
                        <div class="last-elements-card">
                          <div class="pseudo"><%= "#{battle.user.pseudo}" %></div>
                            <div class="status">
                            <% status = if battle.winner %>
                              <%= content_tag(:i, '', class: 'fa-solid fa-trophy') %><%= "#{battle.winner}" %>
                            <% else %>
                              <%= content_tag(:i, '', class: 'fa-solid fa-clock') %>
                              <% seconds_until_target_time = battle.end_date.to_time.to_i - Time.now.to_i %>
                              <%= content_tag(:p, "", data: {
                                    controller: "timer",
                                    timer_target: "timer",
                                    seconds_until_end_value: seconds_until_target_time
                                  }) %>
                            <% end %>
                          </div>
                        </div>
                    </div>
                </div>
              <% end %>
          <% end %>

        </div>

        <div class="button-row">
          <button id="loadLess" class="button-slide" style="display: none">Show less</button>
          <button id="loadMore" class="button-slide">Show more</button>
        </div>

      </div>


    <div class="fourth-row-index">
      <h2 class="second-title">History</h2>
        <div class="index-fourth-row">

          <% @past_battles.each do |battle| %>
              <%= link_to battle_path(battle), class: 'text-decoration-none' do %>
                <div class="prompt-card">
                  <div class="prompt-top"><p><%= battle.prompt %></p></div>

                    <div class="prompt-card-body">
                      <div class="first-elements-card">
                        <div class="category"><%= battle.category.capitalize %></div>
                        <div class="battle-vote-count">
                          <i class="fa-solid fa-check-to-slot"></i>
                          <%= "#{battle.votes.count}" %>
                        </div>
                      </div>
                        <div class="last-elements-card">
                          <div class="pseudo"><%= "#{battle.user.pseudo}" %></div>
                          <div class="status">
                            <% status = if battle.winner %>
                              <%= content_tag(:i, '', class: 'fa-solid fa-trophy') %><%= "#{battle.winner}" %>
                            <% else %>
                              <%= content_tag(:i, '', class: 'fa-solid fa-clock') %>
                              <% seconds_until_target_time = battle.end_date.to_time.to_i - Time.now.to_i %>
                              <%= content_tag(:p, "", data: {
                                    controller: "timer",
                                    timer_target: "timer",
                                    seconds_until_end_value: seconds_until_target_time
                                  }) %>
                            <% end %>
                          </div>
                        </div>
                    </div>
                </div>
              <% end %>
          <% end %>

        </div>

        <div class="button-row"><%= link_to "See all history", history_battles_path, class: 'd-inline-block button-slide' %></div>

    </div>


</div>

app/views/battles/new.html.erb
<div class="container">
<% if user_signed_in? %>
  <h1 class="title-index">New Battle begin</h1>
  <%= render "new_form", battle: @battle %>
<% else %>
<div class="container">
<h1 class="my-5 text-center">Oh wait.. 😒</h1>
<div>
  <p>You need an account in order to start a battle.</p>
  <%= link_to "Log in", new_user_session_path, class: "btn btn-primary" %>
</div>
</div>
<% end %>
</div>

app/views/battles/show.html.erb
<% if DateTime.now < @battle.end_date %>
<%# if @battle.winner.nil? %>

  <div class="user-prompt-and-infos">
    <div class="show-user-prompt">
      <%= @battle.prompt %>
      <div class="show-category">
        <% if @battle.category == "Content generation" %>
          <i class="fa-solid fa-keyboard"></i>
        <% elsif @battle.category == "Research" %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% elsif @battle.category == "Discussion" %>
          <i class="fa-solid fa-comments"></i>
        <% else %>
          <i class="fa-solid fa-calculator"></i>
        <% end %>
      </div>
    </div>
    <div>
      <!-- Timer -->
      <% seconds_until_target_time = @battle.end_date.to_time.to_i - Time.now.to_i %>

      <div class="user-infos-and-timer">
        <div class="timer show-user-infos"><%= content_tag(:h1, "", data: {
          controller: "timer",
          timer_target: "timer",
          seconds_until_end_value: seconds_until_target_time
        }) %></div>
      </div>

      <div class="user-infos-and-timer mt-2">
        <div class="show-user-infos">
          <% if @battle.user.photo.attached?%>
            <%= cl_image_tag @battle.user.photo.key, class: 'avatar-show' %>
          <% else %>
            <%= image_tag "Default_avatar.jpeg", class: 'avatar-show' %>
          <% end %>
            <span class="ms-2"><%= @battle.user.pseudo %></span>
        </div>
      </div>
    </div>
  </div>

  <h2 class="choose text-turquoize-color">Choose the best answer</h2>

  <div class="row-container-show">
    <% @responses.each do |response| %>
        <% if response.content == "API Error" || response.content == "an unknown error has occurred" %>
          <div class="response-card">
            <div class="show-error-card">
              <h5 class="error-card-text">Uh oh ... it seems like this AI won't be able to participate</h5>
              <%= image_tag "error_529_vector.svg" %>
            </div>
          </div>
        <% else %>

            <%= link_to battle_votes_path(@battle, response_id: response.id), data: { turbo_method: :post }, class: "response-card #{'active-vote' if Vote.user_voted?(current_user, @battle) && response == @vote.response}" do %>
            <div class="response-card-scroll">
              <%= render "response", response: response, battle: @battle, user: current_user, vote: @vote %>
            </div>
          <% end %>

        <% end %>

    <% end %>

  </div>

<% else %>

  <h1 class="title-index">This battle is already over</h1>

  <%= button_to "Start a new one", new_battle_path, method: :get, class: "show-start-button" %>
  <div class="user-prompt-and-infos">
    <div>
        <div class="show-user-prompt">
          <%= @battle.prompt %>
          <div class="show-category">
            <% if @battle.category == "Content generation" %>
              <i class="fa-solid fa-keyboard"></i>
            <% elsif @battle.category == "Research" %>
              <i class="fa-solid fa-magnifying-glass"></i>
            <% elsif @battle.category == "Discussion" %>
              <i class="fa-solid fa-comments"></i>
            <% else %>
              <i class="fa-solid fa-calculator"></i>
            <% end %>
          </div>
        </div>
    </div>

    <div>
      <div class="user-infos-and-timer justify-content-between">
        <p class="ms-3 text-gray-color">Closed</p>
        <p class="text-gray-color me-3"><%= @votes_count %> Votes</p>
      </div>

      <div class="user-infos-and-timer mt-2">
        <div class="show-user-infos">
          <% if @battle.user.photo.attached?%>
            <%= cl_image_tag @battle.user.photo.key, class: 'avatar-show' %>
          <% else %>
            <%= image_tag "Default_avatar.jpeg", class: 'avatar-show' %>
          <% end %>
            <span class="ms-2"><%= @battle.user.pseudo %></span>
        </div>
      </div>
    </div>
  </div>


  <div class="chart-container">
    <div class="charts-card">

      <div class="bar-chart">
        <p class="chart-p chart-p-winner">Winner <i class="fa-solid fa-crown"></i></p>
        <canvas data-controller="barchart" data-barchart-ranking-value=<%= @ranking.to_json %> data-barchart-votecount-value=<%= @votes_count_ranking.to_json %>>
        </canvas>
      </div>
      <div class="doughnut-chart">
        <p class="chart-p">Winning rates:</p>
        <canvas data-controller="doughnut" data-doughnut-models-value=<%= @sorted_models.to_json %> data-doughnut-votes-value=<%= @sorted_vote_counts.to_json %>>
        </canvas>
      </div>
    </div>

  </div>

  <div class="row-container-show">
      <% @responses.each do |response| %>

          <% if response.content == "API Error" || response.content == "an unknown error has occurred" %>
            <div class="response-card">
              <div class="show-error-card">
                <h5 class="error-card-text">Sorry, this AI couldn't participate</h5>
                <%= image_tag "error_529_vector.svg" %>
              </div>
            </div>
          <% else %>
            <div class="response-card-podium">
              <div class="response-card-scroll"><%=  %>
                <%= content_tag :p, response.model, class: "text-center fs-3 show-model-response #{ response.model == @ranking.first ? 'yellow-text-color' : 'text-turquoize-color' }" %>
                <p class="margin-token text-gray-color">tokens: <%= response.token %></p>
                <div class="response-content-text-card">
                  <%= markdown_to_html(response.content) %>
                </div>
              </div>
            </div>
          <% end %>

      <% end %>
    </div>
</div></div>
<%# </div> %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta property="og:title" content="<%= meta_title %>">
    <meta property="og:image" content="<%= meta_image %>">
    <!-- etc. -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <% unless current_page?(root_path) || controller_name == "errors"  %>
      <%= render "shared/nnavbar" %>
    <% end %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <% unless current_page?(root_path) || current_page?(new_battle_path) || controller_name == "errors"  %>
      <%= render "shared/upbutton" %>
    <% end %>
    <span class="spacer"></span>
    <% unless current_page?(root_path) || controller_name == "errors"  %>
      <%= render "shared/footer" %>
    <% end %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="py-4 mt-auto">
  <span> © 2025 404 Fighters – All right reserved </span>

  <ul class="footer-links">
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Team", team_path %></li>
    <li><%= link_to "Legal", legal_path %></li>
  </ul>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%# <div class="d-flex justify-content-between"> %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= link_to root_path, class: "anim-link" do %>
        <%= image_tag "Logo_AI-Duel.svg", alt: "logo", width: "40px", height: "40px"%>
      <% end %>
        <ul class="navbar-nav me-auto">
            <li class="nav-item light-text-color active">
              <%#= link_to "HomePage", root_path, class: "nav-link light-text-color" %>
            </li>
            <li class="nav-item light-text-color">
              <%= link_to "New", new_battle_path, class: "nav-link light-text-color" %>
            </li>
            <li class="nav-item light-text-color">
              <% if user_signed_in? %>
                <%= link_to "Index", battles_path, class: "nav-link light-text-color" %>
              <% else %>
                <%= link_to "Index", index_ongoing_battles_path, class: "nav-link light-text-color" %>
              <% end %>
            </li>
            <li class="nav-item light-text-color">
              <% if user_signed_in? %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link light-text-color" %>
              <% else %>
                <%= link_to "Login", new_user_session_path, class: "nav-link light-text-color" %>
              <% end %>
            </li>
        </ul>
      </div>

      <% if user_signed_in? %>
        <div>
          <span class="avatar-text"><%= current_user.pseudo %></span>
          <% if current_user.photo.attached?%>
            <%= cl_image_tag current_user.photo.key, class: 'avatar' %>
          <% else %>
            <%= image_tag "Default_avatar.jpg", class: 'avatar' %>
          <% end %>
        </div>
      <% end %>

  </div>
</div>

app/views/shared/_nnavbar.html.erb
<div class="nav-container">
  <div class="nav-logo">
    <%= link_to root_path, class: "anim-link" do %>
      <%= image_tag "Logo_AI-Duel.svg", alt: "logo", width: "60px", height: "60px"%>
    <% end %>
  </div>
  <div class="nav-links">
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to "My Board", battles_path, class: "nav-link light-text-color #{'active' if current_page?(battles_path)}" %></li>
      <li class="nav-item"><%= link_to "Start Battle", new_battle_path, class: "nav-link light-text-color #{'active' if current_page?(new_battle_path)}" %></li>
      <li class="nav-item"><%= link_to "Opened Battles", index_ongoing_battles_path, class: "nav-link light-text-color #{'active' if current_page?(index_ongoing_battles_path)}" %></li>
      <li class="nav-item"><%= link_to "History", history_battles_path, class: "nav-link light-text-color #{'active' if current_page?(history_battles_path)}" %></li>
    </ul>
  </div>
   <% if user_signed_in? %>
   <div class="nav-avatar">
   <ul class="navbar-nav">
      <li class="nav-item"><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link light-text-color" %></li>
      <li class="nav-item pseudo-nav"><%= current_user.pseudo %></li>
   </ul>
    <% if current_user.photo.attached?%>
      <%= cl_image_tag current_user.photo.key, class: 'avatar' %>
    <% else %>
      <%= image_tag "Default_avatar.jpg", class: 'avatar' %>
    <% end %>
   </div>
   <% end %>
</div>